# Generated by Django 4.2.15 on 2024-08-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="pdfs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("easy_questions", models.IntegerField(default=0)),
                ("medium_questions", models.IntegerField(default=0)),
                ("hard_questions", models.IntegerField(default=0)),
                (
                    "pdf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.pdf"
                    ),
                ),
            ],
        ),
    ]
